{{- if .Values.app.localTrial.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-state
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.app.localTrial.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-provider-keys
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.app.localTrial.storageSize }}
{{- end }}
